I added user posts to the bottom of single blog page.
wsvvrijheid/wsvvrijheid pull request #108
Opened 2022-05-22 17:08 UTC by ertugrul-aydin

2022-05-22 21:58 UTC, 7alip requested changes
Thank you for your work.

Filtering doesn't seem to be working as expected. I left some comments and suggestions. It would be better to add some more draft blogs in the backend to test it properly.

2022-05-22 21:58 UTC, 7alip commented on src/pages/blog/[slug].js
> +  const blogs = await getAuthorBlogs(locale, id)
No need to destructor the id as we don't use it multiple times.

```suggestion
  const blogs = await getAuthorBlogs(locale, blog.author.id, blog.id)
```

2022-05-22 21:58 UTC, 7alip commented on src/services/blog/find.js
> +}
I think it's filtering by `blogId` instead of `authorId`. Besides, we need to filter out the current blog from the result and show latest 3 blogs. It's my suggestion here. Can you test and confirm it?

```js
export const getAuthorBlogs = async (locale, authorID, blogId) => {
  const response = await request({
    url: 'api/blogs',
    filters: {
      $and: [{ author: { id: { $eq: authorID } } }, { id: { $ne: blogId } }],
    },
    sort: ['publishedAt:desc'],
    pageSize: 3,
    locale,
  })

  return response?.result || null
}
```

2022-05-22 22:04 UTC, 7alip commented on src/services/blog/find.js
> +}
@MustafaTRKYLMZ can help here by adding blog data #109

2022-05-22 22:05 UTC, 7alip commented
> It would be better to add some more draft blogs in the backend to test it properly.

@MustafaTRKYLMZ can help here by adding blog data #109

2022-05-22 23:11 UTC, 7alip approved these changes
Perfect! You can merge it when @MustafaTRKYLMZ approves after adding more data and testing.

2022-05-24 18:39 UTC, MustafaTRKYLMZ commented
I think we should see blog authers name end of the blog content before the authers old blogs. Is it possible to add?

2022-05-24 19:04 UTC, 7alip commented
> I think we should see blog authers name end of the blog content before the authers old blogs. Is it possible to add?

I thinks we can add it in another request to be opened for BlogCard. We don't need to keep this pr waiting because of that as we don't have a design for the Card yet

2022-05-26 20:29 UTC, merged