Fix/activity card desc
wsvvrijheid/wsvvrijheid pull request #138
Opened 2022-06-02 20:35 UTC by zahirekrem09

#125

2022-06-02 21:14 UTC, 7alip reviewed
Thank you for the submission. I left a note and I recommend to solve it in the backend.

2022-06-02 21:14 UTC, 7alip commented on src/components/shared/card.js
>          </Text>
I think we don't need to change the card component itself. We actually need to fix it in the backend by providing `description` field as a summary of the context. I was expecting to truncate the content and pass it to `description` prop of the Card.

https://github.com/wsvvrijheid/wsvvrijheid/blob/e360d381aafab81a79696cb5075a02ae7d48f056/src/pages/activities/index.js#L17-L24

`description={activity.content.split(.)}`

But it's also not a good solution as we might have some markdown formatting characters (# * ~ _) in the text. We tried to fix it in another project:

https://github.com/wsvvrijheid/samenvvv/blob/2f5ece9f355ed2b131cc4ae2c081d37893bd6e26/src/utils/makeTwitterContent/index.ts

But my suggestion is that:

Fix the problem in the backend (provide description field of activity). Pass this value to the card.

Shall we keep this PR open until we fix it in the backend?

2022-06-02 22:10 UTC, 7alip requested changes

2022-06-02 22:10 UTC, 7alip commented on src/components/shared/card.js
>          </Text>
Art model has `description` field now. You can try it out @zahirekrem09

2022-06-03 12:05 UTC, zahirekrem09 commented on src/components/shared/card.js
>          </Text>
Updated with the `description` from the backend

2022-06-03 14:49 UTC, MustafaTRKYLMZ approved these changes
Thanks a lot

2022-06-03 16:28 UTC, 7alip requested changes

2022-06-03 16:28 UTC, 7alip commented on src/theme/global.js
> +      maxHeight: '450px',
```suggestion
      width: '100%',
      height: '450px',
```

I think this will fix the issue

2022-06-03 18:11 UTC, 7alip approved these changes
Thank you! You can merge it

2022-06-04 21:25 UTC, merged