feat:added forgot password && reset passsword
wsvvrijheid/wsvvrijheid pull request #89
Opened 2022-04-23 12:53 UTC by zahirekrem09

2022-04-23 13:22 UTC, 7alip reviewed
Excellent work 😎, thank you!

2022-04-23 13:22 UTC, 7alip commented on src/components/forms/forgot-password-form.js
> +  useAuth('/profile', true)
I have some concerns about using `useAuth` in each single components: 

We may have several components in which we render some fields depending on user or user's role. It doesn't seem to me a good solution to always making a request to `/api/me` from each component. I've been considering to call it only in page components instead.

If we would use `isLoggedIn/user/token` from the session in our components, we can pass the value which is obtained in page component via props to nested components. Or we may use `context`, `redux` to share auth data.

I know that it might not be important to move `useAuth` to page component since we have only `forgot-password-form` in the page. But it's better to keep standard for it.

2022-04-23 13:22 UTC, 7alip commented on src/pages/user/forgot-password.js
> +  return (
We can use `useAuth` here

2022-04-23 13:22 UTC, 7alip commented on src/pages/user/reset-password.js
> +  const router = useRouter()
We can use `useAuth` here

2022-04-23 13:22 UTC, 7alip commented on src/components/forms/forgot-password-form.js
> +          <Alert
Shall we add TODO comments for All alerts. We may create a shared Alert component to use for these kind of cases.

2022-04-24 07:41 UTC, 7alip commented on src/components/forms/forgot-password-form.js
> +            <AlertIcon boxSize='40px' mr={0} />
We can leave a little bit space between icon and description (mb={4})

2022-04-24 07:43 UTC, 7alip commented on src/components/forms/reset-password-form.js
> +        router.push('/user/login')
We can add a delay here as well

2022-04-24 07:46 UTC, 7alip commented on src/components/forms/reset-password-form.js
> +          setErrorMessage('')
Wouldn't it better to set the error to initial value which is `null`? We render error alert conditionally.

2022-04-24 07:47 UTC, 7alip requested changes
There are just small changes I've noticed.

2022-04-24 07:49 UTC, 7alip commented on src/pages/user/forgot-password.js
> +const ForgotPassword = ({ seo }) => {
We can use `useAuth` here

2022-04-24 07:49 UTC, 7alip commented on src/pages/user/reset-password.js
> +const ForgotPassword = ({ seo }) => {
We can use `useAuth` here

2022-04-24 08:59 UTC, zahirekrem09 commented on src/components/forms/forgot-password-form.js
> +  useAuth('/profile', true)
Can we solve the problem if we use `useAuth` only in `Layout`?

2022-04-24 10:19 UTC, 7alip approved these changes
Thanks for the update.

Are you assuming to replace the Alert components with toasts that you have created in #90? If not, you can merge both of your PR's

2022-04-24 16:30 UTC, merged